In [27]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

DATA_DIR = '/tmp/data'
NUM_STEPS = 1000
MINIBATCH_SIZE = 100
epochs=10

data = input_data.read_data_sets(DATA_DIR, one_hot=True)

x = tf.placeholder(tf.float32, [None, 784])
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

y_true = tf.placeholder(tf.float32, [None, 10])
y_pred = tf.matmul(x, W) + b

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=y_pred, labels=y_true))


gd_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)

correct_mask = tf.equal(tf.argmax(y_pred, 1), tf.argmax(y_true, 1))
accuracy = tf.reduce_mean(tf.cast(correct_mask, tf.float32))

with tf.Session() as sess:

    # Train
    sess.run(tf.global_variables_initializer())
    for ep in range(epochs):
        for i in range(NUM_STEPS):
            batch_xs, batch_ys = data.train.next_batch(MINIBATCH_SIZE)
            _, accuracy_out = sess.run([gd_step, accuracy], feed_dict={x: batch_xs, y_true: batch_ys})
        print('epoch({:3}) NUM_STEPS({:5}) Accuracy: {}'.format(ep, i, accuracy_out))
    weights, bias = sess.run([W,b])

print("Complete !!!")

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
epoch(  0) NUM_STEPS(  999) Accuracy: 0.8799999952316284
epoch(  1) NUM_STEPS(  999) Accuracy: 0.9100000262260437
epoch(  2) NUM_STEPS(  999) Accuracy: 0.8600000143051147
epoch(  3) NUM_STEPS(  999) Accuracy: 0.9200000166893005
epoch(  4) NUM_STEPS(  999) Accuracy: 0.8899999856948853
epoch(  5) NUM_STEPS(  999) Accuracy: 0.8999999761581421
epoch(  6) NUM_STEPS(  999) Accuracy: 0.9100000262260437
epoch(  7) NUM_STEPS(  999) Accuracy: 0.9200000166893005
epoch(  8) NUM_STEPS(  999) Accuracy: 0.9100000262260437
epoch(  9) NUM_STEPS(  999) Accuracy: 0.9399999976158142
Complete !!!


# 학습모델 저장

In [68]:
import os 
import numpy as np 
MODEL_PATH = './model/' 
np.savez(os.path.join(MODEL_PATH, 'softmax_weight_storage'), weights, bias)

# 저장된 가중치 불러오기

In [69]:
import numpy as np 
import tensorflow as tf 
# 학습된 가중치 불러오기 
MODEL_PATH = './model/' 
loaded_W = np.load(MODEL_PATH + 'softmax_weight_storage.npz') 
loaded_w = loaded_W.items()[0][1] 
loaded_b = loaded_W.items()[1][1] 
print('loaded_w type:{}\nvalue:{}'.format(type(loaded_w), loaded_w))
print('*'*100)
print('loaded_b type:{}\nvalue:{}'.format(type(loaded_b), loaded_b))

loaded_w type:<class 'numpy.ndarray'>
value:[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
****************************************************************************************************
loaded_b type:<class 'numpy.ndarray'>
value:[-0.14281042  0.24421299 -0.02739764 -0.11435637  0.06186947  0.43335503
 -0.02909385  0.2356379  -0.57750654 -0.0839086 ]


# 로딩한 가중치 적용하여 accuracy 확인하기

In [70]:
x = tf.placeholder(tf.float32, [None, 784])
W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

y_true = tf.placeholder(tf.float32, [None, 10])
y_pred = tf.matmul(x, W) + b

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(
    logits=y_pred, labels=y_true))


gd_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)

correct_mask = tf.equal(tf.argmax(y_pred, 1), tf.argmax(y_true, 1))
accuracy = tf.reduce_mean(tf.cast(correct_mask, tf.float32))

with tf.Session() as sess:
    # 로딩한 가중치 적용
    sess.run(W.assign(loaded_w))
    sess.run(b.assign(loaded_b))
    acc = sess.run(accuracy, feed_dict={x:data.test.images, y_true: data.test.labels})
print('Accuracy : {}'.format(acc))

Accuracy : 0.910099983215332
