In [6]:
# 방법 1. Scaler는 각 Feature별로 다른 표준화를 진행한다.
import numpy as np
from sklearn.preprocessing import StandardScaler

data1 = np.array([[1.0 , 2.0 , 3.0 , 4],[19, 10, 11, 12],[5.0 , 6.0 , 7.0, 8.0]])
scaler = StandardScaler()
data2 = scaler.fit_transform(data1)

print(data1)
print(data2)
print('Data1[:,0] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data1[:,0].mean(), data1[:,0].std()))
print('Data2[:,0] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data2[:,0].mean(), data2[:,0].std()))
print('Data1[:,1] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data1[:,1].mean(), data1[:,1].std()))
print('Data2[:,1] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data2[:,1].mean(), data2[:,1].std()))


[[ 1.  2.  3.  4.]
 [19. 10. 11. 12.]
 [ 5.  6.  7.  8.]]
[[-0.95025527 -1.22474487 -1.22474487 -1.22474487]
 [ 1.38218948  1.22474487  1.22474487  1.22474487]
 [-0.43193421  0.          0.          0.        ]]
Data1[:,0] >>> Mean :   8.333333 , STDDEV :   7.717225
Data2[:,0] >>> Mean :  -0.000000 , STDDEV :   1.000000
Data1[:,1] >>> Mean :   6.000000 , STDDEV :   3.265986
Data2[:,1] >>> Mean :   0.000000 , STDDEV :   1.000000


In [5]:
# 방법 2. Scaler는 각 Feature별로 다른 표준화를 진행한다.
from sklearn.preprocessing import scale, robust_scale, minmax_scale, maxabs_scale

data1 = np.array([[1.0 , 2.0 , 3.0 , 4],[19, 10, 11, 12],[5.0 , 6.0 , 7.0, 8.0]])
data2 = scale(data1)

print(data1)
print(data2)
print('Data1[:,0] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data1[:,0].mean(), data1[:,0].std()))
print('Data2[:,0] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data2[:,0].mean(), data2[:,0].std()))
print('Data1[:,1] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data1[:,1].mean(), data1[:,1].std()))
print('Data2[:,1] >>> Mean : {:10.6f} , STDDEV : {:10.6f}'.format(data2[:,1].mean(), data2[:,1].std()))



[[ 1.  2.  3.  4.]
 [19. 10. 11. 12.]
 [ 5.  6.  7.  8.]]
[[-0.95025527 -1.22474487 -1.22474487 -1.22474487]
 [ 1.38218948  1.22474487  1.22474487  1.22474487]
 [-0.43193421  0.          0.          0.        ]]
Data1[:,0] >>> Mean :   8.333333 , STDDEV :   7.717225
Data2[:,0] >>> Mean :  -0.000000 , STDDEV :   1.000000
Data1[:,0] >>> Mean :   6.000000 , STDDEV :   3.265986
Data2[:,0] >>> Mean :   0.000000 , STDDEV :   1.000000


In [16]:
# Scaler는 각 Feature별로 다른 표준화를 진행한다.
from sklearn.preprocessing import scale, robust_scale, minmax_scale, maxabs_scale

data = np.vstack([np.arange(5, dtype=float) - 20, np.arange(5, dtype=float) - 2]).T
data_scale = scale(data)
data_robust_scale = robust_scale(data)
data_minmax_scale = minmax_scale(data)
data_maxabs_scale = maxabs_scale(data)

print('{} <<<<<<<<< data'.format(data))
print('{} <<<<<<<<< data_scale'.format(data_scale))
print('{} <<<<<<<<< data_robust_scale'.format(data_robust_scale))
print('{} <<<<<<<<< data_minmax_scale'.format(data_minmax_scale))
print('{} <<<<<<<<< data_maxabs_scale'.format(data_maxabs_scale))

[[-20.  -2.]
 [-19.  -1.]
 [-18.   0.]
 [-17.   1.]
 [-16.   2.]] <<<<<<<<< data
[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]] <<<<<<<<< data_scale
[[-1.  -1. ]
 [-0.5 -0.5]
 [ 0.   0. ]
 [ 0.5  0.5]
 [ 1.   1. ]] <<<<<<<<< data_robust_scale
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [0.75 0.75]
 [1.   1.  ]] <<<<<<<<< data_minmax_scale
[[-1.   -1.  ]
 [-0.95 -0.5 ]
 [-0.9   0.  ]
 [-0.85  0.5 ]
 [-0.8   1.  ]] <<<<<<<<< data_maxabs_scale


In [21]:
import pandas as pd


0    1
0 -1.0 -1.0
1 -0.5 -0.5
2  0.0  0.0
3  0.5  0.5
4  1.0  1.0

In [23]:
pd.DataFrame(data_scale)

0         1
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [24]:
pd.DataFrame(data_robust_scale)

0    1
0 -1.0 -1.0
1 -0.5 -0.5
2  0.0  0.0
3  0.5  0.5
4  1.0  1.0

In [25]:
pd.DataFrame(data_minmax_scale)

0     1
0  0.00  0.00
1  0.25  0.25
2  0.50  0.50
3  0.75  0.75
4  1.00  1.00

In [22]:
pd.DataFrame(data_maxabs_scale)

0    1
0 -1.00 -1.0
1 -0.95 -0.5
2 -0.90  0.0
3 -0.85  0.5
4 -0.80  1.0

In [ ]:
data_robust_scale = robust_scale(data)
data_minmax_scale = minmax_scale(data)
data_maxabs_scale = maxabs_scale(data)
