In [41]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [31]:
x = np.array(range(25)).reshape(1,5,5,1)

In [51]:
x_pd = x.reshape(5,5)
pd.DataFrame(x_pd,columns = list('ABCDE'))

A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [33]:
x_mp = tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,2,2,1], padding="SAME")

In [34]:
x_mp

<tf.Tensor 'MaxPool_5:0' shape=(1, 3, 3, 1) dtype=int64>

In [35]:
with tf.Session() as sess:
    x_mp_out = sess.run(x_mp)

In [49]:
xx = x_mp_out.reshape(3,3)
pd.DataFrame(xx,columns = list('ABC'))

A   B   C
0   6   8   9
1  16  18  19
2  21  23  24

# aa

In [74]:
x = np.array(range(20))
x  = np.append(x, np.array(range(5))).reshape(1,5,5,1) 

In [75]:
x_pd = x.reshape(5,5)
pd.DataFrame(x_pd,columns = list('ABCDE'))

A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4   0   1   2   3   4

In [78]:
x_mp = tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,2,2,1], padding="SAME")

In [79]:
with tf.Session() as sess:
    x_mp_out = sess.run(x_mp)

In [80]:
xx = x_mp_out.reshape(3,3)
pd.DataFrame(xx,columns = list('ABC'))

A   B   C
0   6   8   9
1  16  18  19
2   1   3   4

In [82]:
x = np.array(range(20))
x  = np.append(x, np.array(range(5))).reshape(1,5,5,1) 

x_pd = x.reshape(5,5)
pd.DataFrame(x_pd,columns = list('ABCDE'))
print(x_pd)

x_mp = tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,2,2,1], padding="SAME")

with tf.Session() as sess:
    x_mp_out = sess.run(x_mp)
    
xx = x_mp_out.reshape(3,3)
pd.DataFrame(xx,columns = list('ABC'))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


A   B   C
0   6   8   9
1  16  18  19
2   1   3   4