In [3]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

In [4]:
# Constant 선언
DATA_DIR = '/tmp/data'
NUM_STEPS = 1000
MINIBATCH_SIZE = 100

In [5]:
# Data Read
data = input_data.read_data_sets(DATA_DIR, one_hot=True) # x는 784배열의 0~1값이고, y는 One Hot Encoding으로 데이터 Read

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [6]:
# x, W 초기화
x = tf.placeholder(tf.float32, [None, 784])
W = tf.Variable(tf.zeros([784, 10]))
y_true = tf.placeholder(tf.float32, [None, 10])

In [7]:
# 계산 그래프
y_pred = tf.matmul(x, W)

In [8]:
# Loss Function(분류에 대해서는 cross entropy를 사용한다. Regression인 경우 MSE를 많이 싸용한따>)
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y_pred, labels=y_true))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



In [9]:
# Gradient Descent
gd_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

In [10]:
# 평가
correct_mask = tf.equal(tf.argmax(y_pred, 1), tf.argmax(y_true, 1))  # 0:열, 1:행, 2:면중에 argmax를 구한다.
accuracy = tf.reduce_mean(tf.cast(correct_mask, tf.float32))

In [11]:
# 실행
with tf.Session() as sess:

    # Train
    sess.run(tf.global_variables_initializer())
    for i in range(NUM_STEPS):
        batch_xs, batch_ys = data.train.next_batch(MINIBATCH_SIZE)
        sess.run(gd_step, feed_dict={x: batch_xs, y_true: batch_ys})
        # Test
        if i % 100 == 0 :
            ans = sess.run(accuracy, feed_dict={x: data.test.images, y_true: data.test.labels})
            print("Accuracy: {:.4}%".format(ans*100))


Accuracy: 34.07%
Accuracy: 88.88%
Accuracy: 90.38%
Accuracy: 90.65%
Accuracy: 91.22%
Accuracy: 90.95%
Accuracy: 91.01%
Accuracy: 91.32%
Accuracy: 91.51%
Accuracy: 91.53%


In [10]:
import tensorflow as tf

x = [[0,0,0,0,1],[0,0,1,0,0]]
with tf.Session() as sess:
    a_0 = tf.argmax(x,0).eval(session=sess) # 열로 봤을때 argmax
    a_1 = tf.argmax(x,1).eval(session=sess) # 행으로 봤을때 argmax
    #a_2 = tf.argmax(x,2).eval(session=sess)
    print(a_0)
    print(a_1)

[0 0 1 0 0]
[4 2]


In [11]:
import tensorflow as tf

x = [[[0,0,0,0,0],[1,0,0,0,0]],
     [[0,1,0,0,0],[0,0,1,0,0]],
     [[0,0,0,1,0],[0,0,0,0,1]]]
with tf.Session() as sess:
    a_0 = tf.argmax(x,0).eval(session=sess) # 열로 봤을때 argmax
    a_1 = tf.argmax(x,1).eval(session=sess) # 행으로 봤을때 argmax
    a_2 = tf.argmax(x,2).eval(session=sess)
    print(a_0)
    print(a_1)
    print(a_2)

[[0 1 0 2 0]
 [0 0 1 0 2]]
[[1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
[[0 0]
 [1 2]
 [3 4]]
